name = "Cobbled Horizon"
author = "Jimmy McCann and contributors"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d631c3521b019272bbbc6671be352ed0de86af26af6deaf864a0e60780c7f9a"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
