name = "Cobbled Horizon"
author = "Jimmy McCann and contributors"
version = "26.2.0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2da4b2b28901d1d037d9ac3867051a0218f5926caf5041d2fbbd1062275ff79d"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
