name = "Cobbled Horizon"
author = "Jimmy McCann and contributors"
version = "26.2.0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58bcd6db40dc1989aa9fe7ba1050eedc9bb15bf72d0694811bb43493c002b48b"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
